/* TEXTOS EN INGLÉS Y FRANCÉS.
   Español: edite los textos en index.html. Cada data-t identifica su traducción.
   Mantenga las mismas claves en EN y FR. No cambie nombres, cifras o credenciales.
   Se admiten únicamente las etiquetas editoriales <br> y <em> escritas aquí.
   El aviso legal español de index.html nunca se sustituye ni se traduce automáticamente. */
window.LAWPEZ_TRANSLATIONS = {
 en: {
  skip:'Skip to content',navApproach:'Approach',navServices:'Services',navYou:'You are',navTeam:'Team',navContact:'Contact',menu:'Menu',closeMenu:'Close',
  consulting:'Immigration consulting · Document preparation',heroLine1:'Navigating the',heroLine2:'immigration system.',heroAside:'With precision,<br>dignity and results.',talk:'Let’s talk',scroll:'Scroll to explore our approach',pauseMotion:'Pause motion',resumeMotion:'Resume motion',
  marquee:'Family Petitions · Adjustment of Status · Asylum & Protection · Work Visas · Naturalization · E-2 Investment · EB-5 · Consular Processing · Venezuelan Law ·',
  humanTechnical:'The human + the technical',approachLine1:'The human and the technical,',approachLine2:'in the same file.',approachCaption:'Attention to detail. Attention to people.',human:'The human side',technical:'The technical side',
  humanBody:'Every case is a life story. Our team understands the urgency, uncertainty and hope behind each petition. We listen first, then offer recommendations.',
  technicalBody:'Founded by a Venezuelan consultant with an LL.M. from Loyola University Chicago. We combine legal rigor with deep cultural empathy and direct knowledge of the Venezuelan legal system.',
  scope:'Consulting and document preparation. We are not attorneys or a law firm.',sixAreas:'Six areas of consulting',servicesLine1:'Six paths,',servicesLine2:'one strategy.',slogan:'We navigate the immigration system with precision, dignity and results.',documentConsulting:'Document consulting',askDocuments:'Ask about documents',
  s1Title:'Family petitions & Adjustment of status',s1Body:'Reunification of spouses, children and parents of U.S. citizens or permanent residents. Complete documentation.',
  s2Title:'Naturalization & Consular processing',s2Body:'N-400 applications, document preparation for naturalization interviews and immigrant visas through consulates and embassies.',
  s3Title:'Asylum & Humanitarian protection',s3Body:'Information gathering for eligibility review by an attorney, I-589 applications, personal statements and documentation. Specialization in Venezuelan cases.',
  s4Title:'Work visas & Change of status',s4Body:'H-1B, L-1, O-1, TN and other categories. Changes of status, extensions and employer petitions.',
  s5Title:'E-2 & EB-5 investor visas',s5Body:'Documentation relating to business planning and investment structuring, and preparation of files for submission by the applicant to consulates. For investors and entrepreneurs.',
  s6Title:'Venezuelan law & Expert letters',s6Body:'Expert letters on the Venezuelan legal system for asylum, degree recognition and document certification.',
  youTitle:'Are you looking to reunite with your family, protect your future, build <em>a new life?</em>',profile0:'an asylum applicant',profile1:'a resident’s family member',profile2:'an investor',profile3:'a professional with a work visa',profile4:'a Venezuelan living abroad',
  youBody:'At Lawpez Strategic Immigration, we review your documentation with honesty and care, regardless of the complexity of your circumstances.',viewService:'Explore the service',statCases:'adjustment of status and family reunification cases managed.',statExperience:'in asylum, family immigration and Venezuelan law.',statResponse:'Response within 24 business hours.',years:'years',
  teamLabel:'Personal attention',teamLine1:'Three people,',teamLine2:'one case file.',teamIntro:'Each client works with all three. No call centers or rotating paralegals.',luisRole:'Founder & Principal Consultant',
  luisBio:'Venezuelan consultant. LL.M. in Comparative Law, Loyola University Chicago (2025). +5 years in asylum, family immigration and Venezuelan law.',sofiaBio:'+200 adjustment of status and family reunification cases managed.',danielCredential:'Doctorate in Political Science (Venezuela)',danielBio:'Political scientist specializing in country conditions analysis for Venezuelan asylum cases. Coordinates case files and documentary evidence.',
  confidential:'Confidential',contactTitle:'Let’s talk.',contactNote:'We respond within 24 business hours. Every inquiry is strictly confidential.',trilingual:'Trilingual',footerScope:'Consulting · We are not attorneys',accepting:'Accepting new cases',legalTitle:'Legal notice',
  legalTranslation:'Lawpez Group LLC is an immigration consulting company. We are NOT attorneys or a law firm. Our services consist of consulting and document preparation. We do not provide legal advice, do not represent clients before immigration courts or the Department of State, and are not licensed to practice law. If you need legal representation, you must retain a licensed immigration attorney. The information on this website is general and informational only and does not constitute legal advice.',
  skylineAlt:'Chicago skyline at sunset',deskAlt:'Documents and pen on a desk',handsAlt:'Hands reviewing documents',dawnAlt:'Evening light beside a window overlooking the city',metaDescription:'Immigration consulting and document preparation. Chicago and Caracas. Service in Spanish, English and French.'
 },
 fr: {
  skip:'Aller au contenu',navApproach:'Approche',navServices:'Services',navYou:'Vous êtes',navTeam:'Équipe',navContact:'Contact',menu:'Menu',closeMenu:'Fermer',
  consulting:'Consultation en immigration · Préparation de documents',heroLine1:'Nous vous guidons',heroLine2:'dans l’immigration.',heroAside:'Avec précision,<br>dignité et résultats.',talk:'Parlons-en',scroll:'Défiler pour connaître notre approche',pauseMotion:'Suspendre les animations',resumeMotion:'Reprendre les animations',
  marquee:'Demandes familiales · Ajustement de statut · Asile & Protection · Visas de travail · Naturalisation · Investissement E-2 · EB-5 · Procédure consulaire · Droit vénézuélien ·',
  humanTechnical:'L’humain + la technique',approachLine1:'L’humain et la technique,',approachLine2:'dans un même dossier.',approachCaption:'Le souci du détail. L’attention aux personnes.',human:'La dimension humaine',technical:'La dimension technique',
  humanBody:'Chaque dossier raconte une histoire de vie. Notre équipe comprend l’urgence, l’incertitude et l’espoir derrière chaque demande. Nous écoutons d’abord, puis formulons nos recommandations.',
  technicalBody:'Fondée par un consultant vénézuélien titulaire d’un LL.M. de Loyola University Chicago. Nous associons rigueur juridique, empathie culturelle et connaissance directe du système juridique vénézuélien.',
  scope:'Consultation et préparation de documents. Nous ne sommes ni avocats ni cabinet d’avocats.',sixAreas:'Six domaines de consultation',servicesLine1:'Six chemins,',servicesLine2:'une stratégie.',slogan:'Nous vous guidons dans le système migratoire avec précision, dignité et résultats.',documentConsulting:'Accompagnement documentaire',askDocuments:'Parlons des documents',
  s1Title:'Demandes familiales & Ajustement de statut',s1Body:'Réunification des conjoints, enfants et parents de citoyens américains ou de résidents permanents. Documentation complète.',
  s2Title:'Naturalisation & Procédure consulaire',s2Body:'Demande N-400, préparation documentaire pour les entretiens de naturalisation et les visas d’immigrant auprès des consulats et ambassades.',
  s3Title:'Asile & Protection humanitaire',s3Body:'Collecte d’informations pour l’examen de l’admissibilité par un avocat, formulaire I-589, déclarations personnelles et documentation. Spécialisation dans les dossiers vénézuéliens.',
  s4Title:'Visas de travail & Changement de statut',s4Body:'H-1B, L-1, O-1, TN et autres catégories. Changements de statut, prolongations et demandes des employeurs.',
  s5Title:'Visas d’investisseur E-2 & EB-5',s5Body:'Documentation relative au plan d’affaires et à la structuration de l’investissement, et préparation des dossiers à présenter par le demandeur aux consulats. Pour les investisseurs et entrepreneurs.',
  s6Title:'Droit vénézuélien & Lettres d’expert',s6Body:'Lettres d’expert sur le système juridique vénézuélien pour l’asile, la reconnaissance des diplômes et la certification de documents.',
  youTitle:'Vous souhaitez retrouver votre famille, protéger votre avenir, construire <em>une nouvelle vie ?</em>',profile0:'demandeur d’asile',profile1:'membre de la famille d’un résident',profile2:'investisseur',profile3:'professionnel titulaire d’un visa de travail',profile4:'Vénézuélien vivant à l’étranger',
  youBody:'Chez Lawpez Strategic Immigration, nous examinons vos documents avec honnêteté et attention, quelle que soit la complexité de votre situation.',viewService:'Voir le service',statCases:'dossiers d’ajustement de statut et de réunification familiale gérés.',statExperience:'en asile, immigration familiale et droit vénézuélien.',statResponse:'Réponse sous 24 heures ouvrables.',years:'ans',
  teamLabel:'Attention personnelle',teamLine1:'Trois personnes,',teamLine2:'un seul dossier.',teamIntro:'Chaque client travaille avec les trois. Sans centres d’appels ni rotation de parajuristes.',luisRole:'Fondateur & Consultant principal',
  luisBio:'Consultant vénézuélien. LL.M. en droit comparé, Loyola University Chicago (2025). +5 ans en asile, immigration familiale et droit vénézuélien.',sofiaBio:'+200 dossiers d’ajustement de statut et de réunification familiale gérés.',danielCredential:'Doctorat en science politique (Venezuela)',danielBio:'Politologue spécialisé dans l’analyse des conditions du pays pour l’asile vénézuélien. Coordonne les dossiers et les preuves documentaires.',
  confidential:'Confidentiel',contactTitle:'Parlons-en.',contactNote:'Nous répondons sous 24 heures ouvrables. Chaque demande est strictement confidentielle.',trilingual:'Trilingue',footerScope:'Consultation · Nous ne sommes pas avocats',accepting:'Nouveaux dossiers acceptés',legalTitle:'Avis juridique',
  legalTranslation:'Lawpez Group LLC est une société de consultation en immigration. Nous ne sommes PAS avocats ni cabinet d’avocats. Nos services comprennent la consultation et la préparation de documents. Nous ne fournissons pas de conseils juridiques, ne représentons pas de clients devant les tribunaux d’immigration ni devant le Département d’État, et ne sommes pas autorisés à exercer le droit. Si vous avez besoin d’une représentation juridique, vous devez engager un avocat en immigration habilité à exercer. Les informations de ce site sont de nature générale et informative uniquement et ne constituent pas un avis juridique.',
  skylineAlt:'Panorama de Chicago au coucher du soleil',deskAlt:'Documents et stylo sur un bureau',handsAlt:'Mains examinant des documents',dawnAlt:'Lumière du soir près d’une fenêtre donnant sur la ville',metaDescription:'Consultation en immigration et préparation de documents. Chicago et Caracas. Services en espagnol, anglais et français.'
 }
};
